#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Wait for postgres
db_ready() {
python << END
import sys
import psycopg2
try:
    conn = psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${PG_HOST}",
        port="${PG_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until db_ready; do
    >&2 echo "Waiting for postgres..."
    sleep 1
done
>2& echo "Postgres is up!!!! :-)"

exec "$@"